
model_dir: /mnt/vast/share/inf2-training/experiments/3.1.2_dpo/job_id_12932/checkpoints/epoch_1

output_dir: tmp/doesntmatter
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${model_dir}/original/tokenizer.model
  max_seq_len: 5120
dataset:
- _component_: torchtune.datasets.medusa_chat_dataset
  source: json
  data_files: /mnt/vast/data/gold/inflection1/prod-fudge-justpi-1-1/openai/sft/justpi_sft_identity_fixed_nosearch_nosys.jsonl
  conversation_column: messages
  train_on_input: True
  packed: False
  conversation_style: openai
  num_medusa_heads: 3
  split: train[:10%]

seed: null
shuffle: true
model:
  _component_: torchtune.models.llama3_1.llama3_1_70b_medusa
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${model_dir}
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00030"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: false
batch_size: 1
epochs: 1
optimizer:
  _component_: torch.optim.AdamW
  lr: 1.0e-04
  fused: true
loss:
  _component_: torchtune.modules.loss.MedusaCrossEntropyLoss
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 20
max_steps_per_epoch: null
gradient_accumulation_steps: 1
device: cuda
enable_activation_checkpointing: true
enable_activation_offloading: true
custom_sharded_layers: ['tok_embeddings', 'output', 'medusa_heads']
# - tok_embeddings
# - output
fsdp_cpu_offload: false #true
compile: false
optimizer_in_bwd: false
dtype: bf16
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  log_dir: ${output_dir}/logs
  project: torchtune
log_every_n_steps: 1
log_peak_memory_stats: true
log_level: INFO
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: false
  output_dir: ${output_dir}/profiling_outputs
  cpu: true
  cuda: true
  profile_memory: false
  with_stack: false
  record_shapes: true
  with_flops: false
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
